/**
 * OpenX 内核加速预设模板字典
 *
 * 500+ 高频代码模板，按类别组织。AI 通过 OX{ID}参数 引用，客户端解码器还原。
 * 模板中 {0} {1} {2} ... 为参数占位符，调用时用 | 分隔传入。
 *
 * ID 命名规则（3-4 字符）：
 *   t01-t99   TypeScript/JavaScript
 *   r01-r99   React / JSX
 *   n01-n99   Node.js
 *   p01-p99   Python
 *   c01-c99   CSS
 *   h01-h99   HTML
 *   j01-j99   JSON
 *   s01-s99   Shell / Bash
 *   q01-q99   SQL
 *   m01-m99   Markdown
 *   x01-x99   工具调用通用（File/Terminal/App 等）
 *   z01-z99   中文高频短语
 *   e01-e99   英文高频短语
 *   o01-o99   操作符 / 标点
 *   cm1-cm9   注释
 *
 * 注意：模板末尾的换行用 \n，避免字符串字面量跨行导致格式错乱。
 */
export const OPENX_PRESET_TEMPLATES: Record<string, string> = {
  // ========== TypeScript / JavaScript 基础（t01-t80）==========
  t01: "import {0} from '{1}'\n",
  t02: 'import {0} from "{1}"\n',
  t03: "import { {0} } from '{1}'\n",
  t04: 'import { {0} } from "{1}"\n',
  t05: "import * as {0} from '{1}'\n",
  t06: "import {0}, { {1} } from '{2}'\n",
  t07: "const {0} = require('{1}')\n",
  t08: 'export {0}\n',
  t09: 'export { {0} }\n',
  t10: 'export default {0}\n',
  t11: 'export default function {0}() {\n',
  t12: 'export default class {0} {\n',
  t13: 'export const {0} = {1}\n',
  t14: 'export function {0}() {\n',
  t15: 'export async function {0}() {\n',
  t16: 'const {0} = {1}\n',
  t17: 'let {0} = {1}\n',
  t18: 'var {0} = {1}\n',
  t19: 'const {0} = ({1}) => {\n',
  t20: 'const {0} = ({1}) => {2}\n',
  t21: 'const {0} = async ({1}) => {\n',
  t22: 'const {0} = () => {1}\n',
  t23: 'function {0}({1}) {\n',
  t24: 'async function {0}({1}) {\n',
  t25: 'function {0}() {\n  {1}\n}\n',
  t26: 'class {0} {\n',
  t27: 'class {0} extends {1} {\n',
  t28: 'interface {0} {\n',
  t29: 'type {0} = {1}\n',
  t30: 'enum {0} {\n',
  t31: 'return {0}\n',
  t32: 'return {0};\n',
  t33: 'await {0}\n',
  t34: 'await {0}({1})\n',
  t35: 'async () => {\n',
  t36: '({0}) => {1}\n',
  t37: '({0}) => ({1})\n',
  t38: 'try {\n  {0}\n} catch (err) {\n  {1}\n}\n',
  t39: 'try {\n  {0}\n} catch ({1}) {\n  {2}\n} finally {\n  {3}\n}\n',
  t40: 'throw new Error({0})\n',
  t41: 'throw new {0}({1})\n',
  t42: 'if ({0}) {\n  {1}\n}\n',
  t43: 'if ({0}) {\n  {1}\n} else {\n  {2}\n}\n',
  t44: 'if ({0}) {\n  {1}\n} else if ({2}) {\n  {3}\n} else {\n  {4}\n}\n',
  t45: 'for (let i = 0; i < {0}; i++) {\n  {1}\n}\n',
  t46: 'for (const {0} of {1}) {\n  {2}\n}\n',
  t47: 'for (const {0} in {1}) {\n  {2}\n}\n',
  t48: 'while ({0}) {\n  {1}\n}\n',
  t49: 'do {\n  {0}\n} while ({1})\n',
  t50: 'switch ({0}) {\n',
  t51: 'case {0}:\n  {1}\n  break;\n',
  t52: 'default:\n  {0}\n  break;\n',
  t53: 'console.log({0})\n',
  t54: 'console.log({0}, {1})\n',
  t55: 'console.error({0})\n',
  t56: 'console.warn({0})\n',
  t57: 'console.info({0})\n',
  t58: 'console.debug({0})\n',
  t59: 'console.table({0})\n',
  t60: 'console.group({0})\n',
  t61: 'console.time({0})\n',
  t62: 'console.timeEnd({0})\n',
  t63: 'console.trace({0})\n',
  t64: 'setTimeout(() => {\n  {0}\n}, {1})\n',
  t65: 'setInterval(() => {\n  {0}\n}, {1})\n',
  t66: 'clearTimeout({0})\n',
  t67: 'clearInterval({0})\n',
  t68: 'Promise.resolve({0})\n',
  t69: 'Promise.reject({0})\n',
  t70: 'Promise.all([{0}])\n',
  t71: 'Promise.allSettled([{0}])\n',
  t72: 'Promise.race([{0}])\n',
  t73: 'new Promise((resolve, reject) => {\n  {0}\n})\n',
  t74: '{0}.then(({1}) => {\n  {2}\n})\n',
  t75: '{0}.then(({1}) => {2}).catch((err) => {\n  {3}\n})\n',
  t76: '{0}.catch((err) => {\n  {1}\n})\n',
  t77: '{0}.finally(() => {\n  {1}\n})\n',
  t78: 'JSON.stringify({0})\n',
  t79: 'JSON.parse({0})\n',
  t80: 'JSON.stringify({0}, null, 2)\n',

  // ========== TypeScript / JavaScript 进阶（t81-t120）==========
  t81: '{0}.map(({1}) => {\n  {2}\n})\n',
  t82: '{0}.filter(({1}) => {\n  {2}\n})\n',
  t83: '{0}.reduce((acc, {1}) => {\n  {2}\n}, {3})\n',
  t84: '{0}.forEach(({1}) => {\n  {2}\n})\n',
  t85: '{0}.find(({1}) => {\n  {2}\n})\n',
  t86: '{0}.some(({1}) => {\n  {2}\n})\n',
  t87: '{0}.every(({1}) => {\n  {2}\n})\n',
  t88: '{0}.includes({1})\n',
  t89: '{0}.indexOf({1})\n',
  t90: '{0}.slice({1})\n',
  t91: '{0}.slice({1}, {2})\n',
  t92: '{0}.splice({1}, {2})\n',
  t93: '{0}.push({1})\n',
  t94: '{0}.pop()\n',
  t95: '{0}.shift()\n',
  t96: '{0}.unshift({1})\n',
  t97: '{0}.join({1})\n',
  t98: '{0}.split({1})\n',
  t99: '{0}.replace({1}, {2})\n',
  taa: '{0}.trim()\n',
  tab: '{0}.substring({1}, {2})\n',
  tac: '{0}.toLowerCase()\n',
  tad: '{0}.toUpperCase()\n',
  tae: 'Object.keys({0})\n',
  taf: 'Object.values({0})\n',
  tag: 'Object.entries({0})\n',
  tah: 'Object.assign({0}, {1})\n',
  tai: 'Object.freeze({0})\n',
  taj: 'const { {0}, {1} } = {2}\n',
  tak: 'const [{0}, {1}] = {2}\n',
  tal: 'typeof {0}\n',
  tam: 'Array.isArray({0})\n',
  tan: 'instanceof {0}\n',
  tao: 'new {0}({1})\n',
  tap: 'delete {0}\n',
  taq: 'typeof {0} === \'{1}\'\n',
  tar: 'Object.keys({0}).length\n',
  tas: 'structuredClone({0})\n',
  tat: 'Math.max({0})\n',
  tau: 'Math.min({0})\n',
  tav: 'Math.floor({0})\n',
  taw: 'Math.ceil({0})\n',
  tax: 'Math.round({0})\n',
  tay: 'Math.random() * {0}\n',

  // ========== React / JSX（r01-r60）==========
  r01: 'import React, { {0} } from \'react\'\n',
  r02: 'import { useState } from \'react\'\n',
  r03: 'import { useEffect } from \'react\'\n',
  r04: 'import { useRef } from \'react\'\n',
  r05: 'import { useMemo } from \'react\'\n',
  r06: 'import { useCallback } from \'react\'\n',
  r07: 'import { useContext } from \'react\'\n',
  r08: 'import { useReducer } from \'react\'\n',
  r09: 'import { useLayoutEffect } from \'react\'\n',
  r10: 'const [{0}, set{1}] = useState({2})\n',
  r11: 'const [{0}, set{1}] = useState(() => {\n  {2}\n})\n',
  r12: 'useEffect(() => {\n  {0}\n}, [{1}])\n',
  r13: 'useEffect(() => {\n  {0}\n  return () => {\n    {1}\n  }\n}, [{2}])\n',
  r14: 'useEffect(() => {\n  {0}\n}, [])\n',
  r15: 'const {0} = useRef({1})\n',
  r16: 'const {0} = useMemo(() => {\n  {1}\n}, [{2}])\n',
  r17: 'const {0} = useCallback(({1}) => {\n  {2}\n}, [{3}])\n',
  r18: 'const {0} = useContext({1})\n',
  r19: 'const [{0}, dispatch] = useReducer({1}, {2})\n',
  r20: 'export function {0}({1}) {\n  return (\n    <div>\n      {2}\n    </div>\n  )\n}\n',
  r21: 'export default function {0}() {\n  return (\n    <div>\n      {1}\n    </div>\n  )\n}\n',
  r22: 'const {0} = ({1}) => {\n  return (\n    <div>\n      {2}\n    </div>\n  )\n}\n',
  r23: 'const {0} = ({1}) => (\n  <div>\n    {2}\n  </div>\n)\n',
  r24: 'interface {0}Props {\n  {1}\n}\n',
  r25: 'type {0}Props = {\n  {1}\n}\n',
  r26: 'export interface {0}Props {\n  {1}: {2}\n}\n',
  r27: 'const {0} = forwardRef(({1}, ref) => {\n  {2}\n})\n',
  r28: 'React.memo(({0}) => {\n  {1}\n})\n',
  r29: 'const {0} = React.memo(({1}) => {\n  {2}\n})\n',
  r30: 'const {0} = React.lazy(() => import(\'{1}\'))\n',
  r31: 'const {0} = ({1}) => {\n  const {2} = useState(false)\n  useEffect(() => {\n    {3}\n  }, [{4}])\n  return (\n    <div>\n      {5}\n    </div>\n  )\n}\n',
  r32: 'onClick={() => {0}}\n',
  r33: 'onChange={({0}) => {1}}\n',
  r34: 'onSubmit={({0}) => {\n  {1}\n}}\n',
  r35: 'className="{0}"\n',
  r36: 'style={{ {0} }}\n',
  r37: 'disabled={{{0}}}\n',
  r38: 'key={{{0}}}\n',
  r39: 'ref={{{0}}}\n',
  r40: '<{0} {1} />\n',
  r41: '<{0}>\n  {1}\n</{0}>\n',
  r42: '<div className="{0}">\n  {1}\n</div>\n',
  r43: '<button onClick={() => {0}}>\n  {1}\n</button>\n',
  r44: '<input type="{0}" value={{{1}}} onChange={{{2}}} />\n',
  r45: '<input\n  type="{0}"\n  value={{{1}}}\n  onChange={{{2}}}\n  placeholder="{3}"\n/>\n',
  r46: '<form onSubmit={{{0}}}>\n  {1}\n</form>\n',
  r47: '<ul>\n  {0}\n</ul>\n',
  r48: '<li key={{{0}}}>\n  {1}\n</li>\n',
  r49: '{items.map((item) => (\n  <div key={item.id}>\n    {0}\n  </div>\n))}\n',
  r50: 'import { createRoot } from \'react-dom/client\'\n',
  r51: 'createRoot(document.getElementById(\'{0}\')!).render({1})\n',
  r52: 'createContext({0})\n',
  r53: 'const {0} = createContext({1})\n',
  r54: 'const {0}Provider = ({ children }) => {\n  {1}\n}\n',
  r55: 'useEffect(() => {\n  const controller = new AbortController()\n  {0}\n  return () => controller.abort()\n}, [{1}])\n',
  r56: 'const [{0}, set{1}] = useState<{2}>(null)\n',
  r57: 'import { useNavigate } from \'react-router-dom\'\n',
  r58: 'import { useParams } from \'react-router-dom\'\n',
  r59: 'import { Link } from \'react-router-dom\'\n',
  r60: 'import { useStore } from \'zustand\'\n',

  // ========== Node.js / 内置模块（n01-n35）==========
  n01: "const fs = require('fs')\n",
  n02: "const path = require('path')\n",
  n03: "const http = require('http')\n",
  n04: "const https = require('https')\n",
  n05: "const os = require('os')\n",
  n06: "const url = require('url')\n",
  n07: "const crypto = require('crypto')\n",
  n08: "const util = require('util')\n",
  n09: "const stream = require('stream')\n",
  n10: "const events = require('events')\n",
  n11: "const child_process = require('child_process')\n",
  n12: 'const {0} = require(\'{1}\')\n',
  n13: 'module.exports = {0}\n',
  n14: 'module.exports = {\n  {0}\n}\n',
  n15: 'module.exports = function ({0}) {\n  {1}\n}\n',
  n16: "const { readFile, writeFile } = require('fs/promises')\n",
  n17: 'await fs.promises.readFile({0}, \'utf-8\')\n',
  n18: 'await fs.promises.writeFile({0}, {1})\n',
  n19: 'fs.readFileSync({0}, \'utf-8\')\n',
  n20: 'fs.writeFileSync({0}, {1})\n',
  n21: 'path.join({0})\n',
  n22: 'path.resolve({0})\n',
  n23: 'path.dirname({0})\n',
  n24: 'path.basename({0})\n',
  n25: 'path.extname({0})\n',
  n26: 'process.env.{0}\n',
  n27: 'process.argv\n',
  n28: 'process.cwd()\n',
  n29: 'process.exit({0})\n',
  n30: 'process.on(\'{0}\', () => {\n  {1}\n})\n',
  n31: 'const {0} = new EventEmitter()\n',
  n32: 'crypto.randomUUID()\n',
  n33: 'crypto.createHash(\'sha256\').update({0}).digest(\'hex\')\n',
  n34: "const { exec, spawn } = require('child_process')\n",
  n35: 'exec(\'{0}\', (err, stdout, stderr) => {\n  {1}\n})\n',

  // ========== Python 基础（p01-p70）==========
  p01: 'import {0}\n',
  p02: 'from {0} import {1}\n',
  p03: 'import {0} as {1}\n',
  p04: 'from {0} import {1} as {2}\n',
  p05: 'def {0}():\n    {1}\n',
  p06: 'def {0}({1}):\n    {2}\n',
  p07: 'def {0}({1}) -> {2}:\n    {3}\n',
  p08: 'async def {0}():\n    {1}\n',
  p09: 'async def {0}({1}):\n    {2}\n',
  p10: 'class {0}:\n    {1}\n',
  p11: 'class {0}({1}):\n    {2}\n',
  p12: 'class {0}:\n    def __init__(self, {1}):\n        {2}\n',
  p13: 'class {0}:\n    def __init__(self):\n        {1}\n',
  p14: '    def {0}(self, {1}):\n        {2}\n',
  p15: '    def {0}(self):\n        {1}\n',
  p16: '    @property\n    def {0}(self):\n        {1}\n',
  p17: '    @staticmethod\n    def {0}({1}):\n        {2}\n',
  p18: '    @classmethod\n    def {0}(cls, {1}):\n        {2}\n',
  p19: 'if {0}:\n    {1}\n',
  p20: 'if {0}:\n    {1}\nelse:\n    {2}\n',
  p21: 'if {0}:\n    {1}\nelif {2}:\n    {3}\nelse:\n    {4}\n',
  p22: 'for {0} in {1}:\n    {2}\n',
  p23: 'for {0} in range({1}):\n    {2}\n',
  p24: 'for {0}, {1} in enumerate({2}):\n    {3}\n',
  p25: 'for {0}, {1} in {2}.items():\n    {3}\n',
  p26: 'while {0}:\n    {1}\n',
  p27: 'try:\n    {0}\nexcept Exception as e:\n    {1}\n',
  p28: 'try:\n    {0}\nexcept {1} as e:\n    {2}\n',
  p29: 'try:\n    {0}\nexcept {1}:\n    {2}\nfinally:\n    {3}\n',
  p30: 'raise {0}({1})\n',
  p31: 'raise {0}\n',
  p32: 'with open({0}) as f:\n    {1}\n',
  p33: 'with open({0}, \'r\', encoding=\'utf-8\') as f:\n    {1}\n',
  p34: 'with open({0}, \'w\', encoding=\'utf-8\') as f:\n    f.write({1})\n',
  p35: 'lambda {0}: {1}\n',
  p36: '@{0}\ndef {1}():\n    {2}\n',
  p37: '@{0}\nasync def {1}():\n    {2}\n',
  p38: 'print({0})\n',
  p39: 'print(f"{0}")\n',
  p40: 'print({0}, {1})\n',
  p41: 'return {0}\n',
  p42: 'pass\n',
  p43: 'break\n',
  p44: 'continue\n',
  p45: 'import asyncio\n',
  p46: 'asyncio.run({0})\n',
  p47: 'await {0}\n',
  p48: 'await {0}({1})\n',
  p49: 'asyncio.gather({0})\n',
  p50: 'asyncio.sleep({0})\n',
  p51: 'import os\n',
  p52: 'import sys\n',
  p53: 'import json\n',
  p54: 'import re\n',
  p55: 'import time\n',
  p56: 'import datetime\n',
  p57: 'import logging\n',
  p58: 'import pathlib\n',
  p59: 'import typing\n',
  p60: 'from typing import {0}\n',
  p61: 'from typing import List, Dict, Optional\n',
  p62: 'def {0}({1}: {2}) -> {3}:\n    {4}\n',
  p63: 'def {0}({1}: str) -> None:\n    {2}\n',
  p64: '{0}: {1}\n',
  p65: '{0}: {1} = {2}\n',
  p66: 'if __name__ == \'__main__\':\n    {0}\n',
  p67: '__name__\n',
  p68: '__init__\n',
  p69: '__main__\n',
  p70: 'self.{0} = {1}\n',

  // ========== Python 进阶（p71-p100）==========
  p71: '[{0} for {1} in {2}]\n',
  p72: '[{0} for {1} in {2} if {3}]\n',
  p73: '{{{0}: {1} for {2} in {3}}}\n',
  p74: '({0} for {1} in {2})\n',
  p75: 'list({0})\n',
  p76: 'dict({0})\n',
  p77: 'set({0})\n',
  p78: 'tuple({0})\n',
  p79: 'len({0})\n',
  p80: 'range({0})\n',
  p81: 'range({0}, {1})\n',
  p82: 'enumerate({0})\n',
  p83: 'zip({0}, {1})\n',
  p84: 'map({0}, {1})\n',
  p85: 'filter({0}, {1})\n',
  p86: 'sorted({0})\n',
  p87: 'sorted({0}, key=lambda x: {1})\n',
  p88: 'reversed({0})\n',
  p89: 'sum({0})\n',
  p90: 'min({0})\n',
  p91: 'max({0})\n',
  p92: 'any({0})\n',
  p93: 'all({0})\n',
  p94: '{0}.append({1})\n',
  p95: '{0}.extend({1})\n',
  p96: '{0}.pop()\n',
  p97: '{0}.split({1})\n',
  p98: '{0}.join({1})\n',
  p99: '{0}.strip()\n',
  paa: '{0}.replace({1}, {2})\n',
  pab: 'f\'{0}\'\n',
  pac: 'f"{0}"\n',
  pad: 'json.dumps({0})\n',
  pae: 'json.loads({0})\n',
  paf: 'os.path.join({0})\n',
  pag: 'os.path.exists({0})\n',
  pah: 'os.makedirs({0}, exist_ok=True)\n',
  pai: '@dataclass\nclass {0}:\n    {1}\n',
  paj: 'from dataclasses import dataclass\n',

  // ========== CSS（c01-c50）==========
  c01: 'display: flex;\n',
  c02: 'display: grid;\n',
  c03: 'display: block;\n',
  c04: 'display: inline-block;\n',
  c05: 'display: none;\n',
  c06: 'flex-direction: column;\n',
  c07: 'flex-direction: row;\n',
  c08: 'justify-content: center;\n',
  c09: 'justify-content: space-between;\n',
  c10: 'justify-content: flex-start;\n',
  c11: 'justify-content: flex-end;\n',
  c12: 'align-items: center;\n',
  c13: 'align-items: flex-start;\n',
  c14: 'align-items: flex-end;\n',
  c15: 'gap: {0};\n',
  c16: 'gap: {0}px;\n',
  c17: 'gap: {0}rem;\n',
  c18: 'margin: 0;\n',
  c19: 'margin: {0};\n',
  c20: 'margin: {0}px;\n',
  c21: 'padding: {0};\n',
  c22: 'padding: {0}px;\n',
  c23: 'padding: {0}px {1}px;\n',
  c24: 'width: {0};\n',
  c25: 'width: {0}px;\n',
  c26: 'width: 100%;\n',
  c27: 'height: {0};\n',
  c28: 'height: {0}px;\n',
  c29: 'height: 100%;\n',
  c30: 'color: {0};\n',
  c31: 'background-color: {0};\n',
  c32: 'background: {0};\n',
  c33: 'border: 1px solid {0};\n',
  c34: 'border-radius: {0}px;\n',
  c35: 'border: none;\n',
  c36: 'font-size: {0}px;\n',
  c37: 'font-size: {0}rem;\n',
  c38: 'font-weight: {0};\n',
  c39: 'font-weight: bold;\n',
  c40: 'text-align: center;\n',
  c41: 'text-align: left;\n',
  c42: 'text-align: right;\n',
  c43: 'position: absolute;\n',
  c44: 'position: relative;\n',
  c45: 'position: fixed;\n',
  c46: 'top: {0}px;\n',
  c47: 'left: {0}px;\n',
  c48: 'right: {0}px;\n',
  c49: 'bottom: {0}px;\n',
  c50: 'z-index: {0};\n',

  // ========== HTML（h01-h30）==========
  h01: '<!DOCTYPE html>\n<html>\n  <head>\n    {0}\n  </head>\n  <body>\n    {1}\n  </body>\n</html>\n',
  h02: '<html lang="zh-CN">\n  {0}\n</html>\n',
  h03: '<head>\n  <meta charset="UTF-8">\n  <title>{0}</title>\n</head>\n',
  h04: '<meta charset="UTF-8">\n',
  h05: '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n',
  h06: '<meta name="description" content="{0}">\n',
  h07: '<title>{0}</title>\n',
  h08: '<link rel="stylesheet" href="{0}">\n',
  h09: '<script src="{0}"></script>\n',
  h10: '<script type="module" src="{0}"></script>\n',
  h11: '<div>\n  {0}\n</div>\n',
  h12: '<span>{0}</span>\n',
  h13: '<p>{0}</p>\n',
  h14: '<h1>{0}</h1>\n',
  h15: '<h2>{0}</h2>\n',
  h16: '<h3>{0}</h3>\n',
  h17: '<a href="{0}">{1}</a>\n',
  h18: '<img src="{0}" alt="{1}">\n',
  h19: '<ul>\n  <li>{0}</li>\n</ul>\n',
  h20: '<ol>\n  <li>{0}</li>\n</ol>\n',
  h21: '<table>\n  <tr>\n    <th>{0}</th>\n  </tr>\n</table>\n',
  h22: '<form action="{0}" method="post">\n  {1}\n</form>\n',
  h23: '<input type="text" name="{0}" placeholder="{1}">\n',
  h24: '<button type="submit">{0}</button>\n',
  h25: '<label for="{0}">{1}</label>\n',
  h26: '<select name="{0}">\n  <option value="{1}">{2}</option>\n</select>\n',
  h27: '<textarea name="{0}" rows="{1}" cols="{2}"></textarea>\n',
  h28: '<nav>\n  {0}\n</nav>\n',
  h29: '<header>\n  {0}\n</header>\n',
  h30: '<footer>\n  {0}\n</footer>\n',

  // ========== JSON（j01-j25）==========
  j01: '{{\n  "{0}": {1}\n}}\n',
  j02: '{{\n  "{0}": {1},\n  "{2}": {3}\n}}\n',
  j03: '{{\n  "{0}": "{1}"\n}}\n',
  j04: '{{\n  "{0}": {1},\n  "{2}": "{3}"\n}}\n',
  j05: '[\n  {0}\n]\n',
  j06: '[\n  {{\n    "{0}": {1}\n  }}\n]\n',
  j07: '{{\n  "name": "{0}",\n  "version": "{1}"\n}}\n',
  j08: '{{\n  "type": "{0}",\n  "data": {1}\n}}\n',
  j09: '{{\n  "code": 0,\n  "data": {0},\n  "message": "success"\n}}\n',
  j10: '{{\n  "code": 1,\n  "message": "{0}"\n}}\n',
  j11: '{{\n  "success": true,\n  "data": {0}\n}}\n',
  j12: '{{\n  "success": false,\n  "error": "{0}"\n}}\n',
  j13: '{{\n  "id": "{0}",\n  "name": "{1}"\n}}\n',
  j14: '{{\n  "items": [\n    {0}\n  ],\n  "total": {1}\n}}\n',
  j15: '{{\n  "status": "{0}",\n  "message": "{1}"\n}}\n',
  j16: '{{\n  "data": {{\n    {0}\n  }}\n}}\n',
  j17: '{{\n  "timestamp": "{0}",\n  "event": "{1}"\n}}\n',
  j18: '{{\n  "user": {{\n    "id": "{0}",\n    "name": "{1}"\n  }}\n}}\n',
  j19: '{{\n  "config": {{\n    {0}\n  }}\n}}\n',
  j20: '{{\n  "request": {{\n    "method": "{0}",\n    "url": "{1}"\n  }}\n}}\n',
  j21: '{{\n  "response": {{\n    "status": {0},\n    "body": {1}\n  }}\n}}\n',
  j22: '{{\n  "{0}": [\n    {1}\n  ]\n}}\n',
  j23: '{{\n  "error": {{\n    "code": "{0}",\n    "message": "{1}"\n  }}\n}}\n',
  j24: '{{\n  "meta": {{\n    "page": {0},\n    "pageSize": {1}\n  }}\n}}\n',
  j25: '{{\n  "{0}": {{\n    "{1}": {2}\n  }}\n}}\n',

  // ========== Shell / Bash（s01-s35）==========
  s01: '#!/bin/bash\n',
  s02: '#!/bin/sh\n',
  s03: '#!/usr/bin/env python3\n',
  s04: '#!/usr/bin/env node\n',
  s05: 'echo "{0}"\n',
  s06: 'echo {0}\n',
  s07: 'cd {0}\n',
  s08: 'mkdir -p {0}\n',
  s09: 'rm -rf {0}\n',
  s10: 'cp {0} {1}\n',
  s11: 'cp -r {0} {1}\n',
  s12: 'mv {0} {1}\n',
  s13: 'touch {0}\n',
  s14: 'cat {0}\n',
  s15: 'cat {0} | grep {1}\n',
  s16: 'ls -la\n',
  s17: 'ls -lh {0}\n',
  s18: 'pwd\n',
  s19: 'which {0}\n',
  s20: 'find {0} -name "{1}"\n',
  s21: 'find {0} -type f -name "{1}"\n',
  s22: 'grep -r "{0}" {1}\n',
  s23: 'grep -rn "{0}" {1}\n',
  s24: 'chmod +x {0}\n',
  s25: 'chmod 755 {0}\n',
  s26: 'chown {0}:{1} {2}\n',
  s27: 'tar -czf {0}.tar.gz {1}\n',
  s28: 'tar -xzf {0}.tar.gz\n',
  s29: 'curl -X GET {0}\n',
  s30: 'curl -X POST {0} -H "Content-Type: application/json" -d \'{1}\'\n',
  s31: 'wget {0}\n',
  s32: 'export {0}={1}\n',
  s33: 'if [ {0} ]; then\n  {1}\nfi\n',
  s34: 'for i in {0}; do\n  {1}\ndone\n',
  s35: 'while {0}; do\n  {1}\ndone\n',

  // ========== SQL（q01-q30）==========
  q01: 'SELECT * FROM {0}\n',
  q02: 'SELECT {0} FROM {1}\n',
  q03: 'SELECT {0} FROM {1} WHERE {2} = {3}\n',
  q04: 'SELECT {0} FROM {1} WHERE {2}\n',
  q05: 'SELECT {0} FROM {1} ORDER BY {2} DESC\n',
  q06: 'SELECT {0} FROM {1} ORDER BY {2} ASC\n',
  q07: 'SELECT {0} FROM {1} LIMIT {2}\n',
  q08: 'SELECT {0} FROM {1} LIMIT {2} OFFSET {3}\n',
  q09: 'INSERT INTO {0} ({1}) VALUES ({2})\n',
  q10: 'INSERT INTO {0} ({1}) VALUES ({2}), ({3})\n',
  q11: 'UPDATE {0} SET {1} = {2} WHERE {3} = {4}\n',
  q12: 'DELETE FROM {0} WHERE {1} = {2}\n',
  q13: 'SELECT COUNT(*) FROM {0}\n',
  q14: 'SELECT COUNT(*) FROM {0} WHERE {1}\n',
  q15: 'SELECT {0} FROM {1} JOIN {2} ON {1}.{3} = {2}.{4}\n',
  q16: 'SELECT {0} FROM {1} LEFT JOIN {2} ON {1}.{3} = {2}.{4}\n',
  q17: 'SELECT {0} FROM {1} GROUP BY {2}\n',
  q18: 'SELECT {0}, COUNT(*) FROM {1} GROUP BY {0}\n',
  q19: 'SELECT {0} FROM {1} HAVING {2}\n',
  q20: 'CREATE TABLE {0} (\n  id INTEGER PRIMARY KEY,\n  {1}\n)\n',
  q21: 'CREATE INDEX idx_{0} ON {1} ({2})\n',
  q22: 'DROP TABLE {0}\n',
  q23: 'ALTER TABLE {0} ADD COLUMN {1} {2}\n',
  q24: 'BEGIN TRANSACTION;\n  {0}\nCOMMIT;\n',
  q25: 'SELECT * FROM {0} WHERE {1} LIKE \'%{2}%\'\n',
  q26: 'SELECT * FROM {0} WHERE {1} IN ({2})\n',
  q27: 'SELECT * FROM {0} WHERE {1} BETWEEN {2} AND {3}\n',
  q28: 'SELECT DISTINCT {0} FROM {1}\n',
  q29: 'SELECT {0} FROM {1} WHERE {2} IS NULL\n',
  q30: 'SELECT {0} FROM {1} WHERE {2} IS NOT NULL\n',

  // ========== Markdown（m01-m25）==========
  m01: '# {0}\n\n',
  m02: '## {0}\n\n',
  m03: '### {0}\n\n',
  m04: '#### {0}\n\n',
  m05: '##### {0}\n\n',
  m06: '**{0}**\n',
  m07: '*{0}*\n',
  m08: '`{0}`\n',
  m09: '~~{0}~~\n',
  m10: '> {0}\n',
  m11: '- {0}\n',
  m12: '1. {0}\n',
  m13: '- [ ] {0}\n',
  m14: '- [x] {0}\n',
  m15: '[{0}]({1})\n',
  m16: '![{0}]({1})\n',
  m17: '```\n{0}\n```\n',
  m18: '```{0}\n{1}\n```\n',
  m19: '```typescript\n{0}\n```\n',
  m20: '```python\n{0}\n```\n',
  m21: '| {0} | {1} |\n| --- | --- |\n',
  m22: '---\n',
  m23: '---\n\n## {0}\n\n',
  m24: '## {0}\n\n{1}\n',
  m25: '> [!NOTE]\n> {0}\n',

  // ========== 工具调用通用（x01-x45）==========
  x01: '{"action": "read", "path": "{0}"}\n',
  x02: '{"action": "write", "path": "{0}", "content": "{1}"}\n',
  x03: '{"action": "list", "path": "{0}"}\n',
  x04: '{"action": "list", "path": "{0}", "recursive": false}\n',
  x05: '{"action": "list", "path": "{0}", "recursive": true}\n',
  x06: '{"action": "search", "path": "{0}", "pattern": "{1}"}\n',
  x07: '{"action": "mkdir", "path": "{0}"}\n',
  x08: '{"action": "delete", "path": "{0}"}\n',
  x09: '{"action": "move", "source": "{0}", "destination": "{1}"}\n',
  x10: '{"action": "copy", "source": "{0}", "destination": "{1}"}\n',
  x11: '{"action": "stat", "path": "{0}"}\n',
  x12: '{"action": "append", "path": "{0}", "content": "{1}"}\n',
  x13: '{"action": "create", "shell": "cmd.exe", "cwd": "{0}"}\n',
  x14: '{"action": "create", "shell": "powershell.exe", "cwd": "{0}"}\n',
  x15: '{"action": "create", "shell": "bash", "cwd": "{0}"}\n',
  x16: '{"action": "send", "terminalId": "{0}", "data": "{1}"}\n',
  x17: '{"action": "sendKey", "terminalId": "{0}", "key": "{1}"}\n',
  x18: '{"action": "output", "terminalId": "{0}", "lines": {1}}\n',
  x19: '{"action": "output", "terminalId": "{0}"}\n',
  x20: '{"action": "close", "terminalId": "{0}"}\n',
  x21: '{"action": "list"}\n',
  x22: '{"action": "open", "app": "{0}"}\n',
  x23: '{"action": "open", "path": "{0}"}\n',
  x24: '{"action": "focus", "title": "{0}"}\n',
  x25: '{"action": "close", "title": "{0}"}\n',
  x26: '{"action": "screenshot"}\n',
  x27: '{"action": "snapshot"}\n',
  x28: '{"action": "click", "x": {0}, "y": {1}}\n',
  x29: '{"action": "type", "text": "{0}"}\n',
  x30: '{"action": "type", "x": {0}, "y": {1}, "text": "{2}"}\n',
  x31: '{"action": "press_key", "key": "{0}"}\n',
  x32: '{"action": "shortcut", "keys": ["{0}", "{1}"]}\n',
  x33: '{"action": "scroll", "direction": "down"}\n',
  x34: '{"action": "create"}\n',
  x35: '{"action": "add", "text": "{0}"}\n',
  x36: '{"action": "complete", "id": "{0}"}\n',
  x37: '{"action": "all"}\n',
  x38: '{"action": "ping", "host": "{0}", "count": {1}}\n',
  x39: '{"action": "portcheck", "host": "{0}", "port": {1}}\n',
  x40: '{"query": "{0}", "num": {1}}\n',
  x41: '{"url": "{0}"}\n',
  x42: '{"url": "{0}", "maxLength": {1}}\n',
  x43: '{"action": "compress", "source": "{0}", "destination": "{1}"}\n',
  x44: '{"action": "extract", "source": "{0}", "destination": "{1}"}\n',
  x45: '{"action": "get", "name": "{0}"}\n',

  // ========== 中文高频短语（z01-z40）==========
  z01: '执行成功\n',
  z02: '执行失败\n',
  z03: '操作完成\n',
  z04: '任务已完成\n',
  z05: '已打开\n',
  z06: '已关闭\n',
  z07: '已创建\n',
  z08: '已删除\n',
  z09: '已写入\n',
  z10: '已读取\n',
  z11: '请稍等\n',
  z12: '请确认\n',
  z13: '正在执行\n',
  z14: '正在处理\n',
  z15: '正在打开\n',
  z16: '正在搜索\n',
  z17: '搜索完成\n',
  z18: '未找到\n',
  z19: '已找到\n',
  z20: '文件已保存\n',
  z21: '命令已执行\n',
  z22: '输出结果如下\n',
  z23: '步骤如下\n',
  z24: '总结\n',
  z25: '完成\n',
  z26: '失败\n',
  z27: '错误\n',
  z28: '警告\n',
  z29: '提示\n',
  z30: '注意事项\n',
  z31: '需要用户确认\n',
  z32: '高风险操作\n',
  z33: '下一步\n',
  z34: '已复制到剪贴板\n',
  z35: '已截图\n',
  z36: '已输入\n',
  z37: '已点击\n',
  z38: '操作成功完成，结果如下：\n',
  z39: '发生错误，请检查以下内容：\n',
  z40: '以下是详细步骤：\n',

  // ========== 英文高频短语（e01-e30）==========
  e01: 'The quick brown fox\n',
  e02: 'function {0}()\n',
  e03: 'return {0};\n',
  e04: 'console.log({0});\n',
  e05: 'import {0} from \'{1}\'\n',
  e06: 'export default {0}\n',
  e07: 'async/await\n',
  e08: 'Promise\n',
  e09: 'callback\n',
  e10: 'undefined\n',
  e11: 'null\n',
  e12: 'true\n',
  e13: 'false\n',
  e14: 'this\n',
  e15: 'self\n',
  e16: 'super\n',
  e17: 'extends\n',
  e18: 'implements\n',
  e19: 'interface\n',
  e20: 'class\n',
  e21: 'function\n',
  e22: 'const\n',
  e23: 'let\n',
  e24: 'var\n',
  e25: 'async\n',
  e26: 'await\n',
  e27: 'yield\n',
  e28: 'throw\n',
  e29: 'catch\n',
  e30: 'finally\n',

  // ========== 操作符 / 标点（o01-o30）==========
  o01: '();\n',
  o02: '({0})\n',
  o03: '({0}, {1})\n',
  o04: '({0}, {1}, {2})\n',
  o05: '[{0}]\n',
  o06: '[{0}, {1}]\n',
  o07: '{{\n  {0}\n}}\n',
  o08: '{{ {0} }}\n',
  o09: '{{ {0}: {1} }}\n',
  o10: ' => {\n',
  o11: ' => {0}\n',
  o12: ' => ({0})\n',
  o13: ' => {0}()\n',
  o14: ' = {0}\n',
  o15: ' === {0}\n',
  o16: ' !== {0}\n',
  o17: ' == {0}\n',
  o18: ' != {0}\n',
  o19: ' && {0}\n',
  o20: ' || {0}\n',
  o21: ' ? {0} : {1}\n',
  o22: ' += {0}\n',
  o23: ' -= {0}\n',
  o24: ' *= {0}\n',
  o25: ' /= {0}\n',
  o26: '++{0}\n',
  o27: '{0}++\n',
  o28: '--{0}\n',
  o29: '{0}--\n',
  o30: '...{0}\n',

  // ========== 注释（cm1-cm15）==========
  cm1: '// {0}\n',
  cm2: '// TODO: {0}\n',
  cm3: '// FIXME: {0}\n',
  cm4: '// NOTE: {0}\n',
  cm5: '// WARNING: {0}\n',
  cm6: '/* {0} */\n',
  cm7: '/*\n * {0}\n */\n',
  cm8: '/**\n * {0}\n */\n',
  cm9: '# {0}\n',
  cma: '# TODO: {0}\n',
  cmb: '# FIXME: {0}\n',
  cmc: '<!-- {0} -->\n',
  cmd: '<!--\n  {0}\n-->\n',
  cme: '"""\n{0}\n"""\n',
  cmf: "'''\n{0}\n'''\n",

  // ========== Electron / 主进程常用（el1-el20）==========
  el1: "const { app, BrowserWindow } = require('electron')\n",
  el2: 'app.whenReady().then(() => {\n  {0}\n})\n',
  el3: 'app.on(\'window-all-closed\', () => {\n  {0}\n})\n',
  el4: 'app.on(\'activate\', () => {\n  {0}\n})\n',
  el5: 'ipcMain.handle(\'{0}\', async (event, {1}) => {\n  {2}\n})\n',
  el6: 'ipcMain.on(\'{0}\', (event, {1}) => {\n  {2}\n})\n',
  el7: 'const mainWindow = new BrowserWindow({\n  width: {0},\n  height: {1},\n  webPreferences: {2}\n})\n',
  el8: 'mainWindow.loadURL(\'{0}\')\n',
  el9: 'mainWindow.loadFile(\'{0}\')\n',
  el10: 'mainWindow.webContents.openDevTools()\n',
  el11: 'const { ipcMain } = require(\'electron\')\n',
  el12: 'const { dialog } = require(\'electron\')\n',
  el13: 'const { Menu } = require(\'electron\')\n',
  el14: 'const { Tray } = require(\'electron\')\n',
  el15: 'app.quit()\n',
  el16: 'app.relaunch()\n',
  el17: "const { shell } = require('electron')\n",
  el18: 'shell.openExternal(\'{0}\')\n',
  el19: 'dialog.showMessageBox({\n  message: \'{0}\'\n})\n',
  el20: 'BrowserWindow.getAllWindows()\n',

  // ========== 配置文件常用（cf1-cf15）==========
  cf1: '{{\n  "name": "{0}",\n  "version": "{1}",\n  "main": "{2}"\n}}\n',
  cf2: '{{\n  "scripts": {{\n    "{0}": "{1}"\n  }}\n}}\n',
  cf3: '{{\n  "dependencies": {{\n    "{0}": "{1}"\n  }}\n}}\n',
  cf4: '{{\n  "devDependencies": {{\n    "{0}": "{1}"\n  }}\n}}\n',
  cf5: 'module.exports = {{\n  {0}\n}}\n',
  cf6: 'export default {\n  {0}\n}\n',
  cf7: '[{0}]\n',
  cf8: '{{\n  "env": {{\n    {0}\n  }}\n}}\n',
  cf9: '{{\n  "extends": "{0}"\n}}\n',
  cf10: '{{\n  "compilerOptions": {{\n    {0}\n  }}\n}}\n',
  cf11: '{{\n  "name": "{0}",\n  "version": "1.0.0",\n  "description": "{1}"\n}}\n',
  cf12: '{{\n  "name": "{0}",\n  "version": "{1}",\n  "type": "module"\n}}\n',
  cf13: '{{\n  "private": true,\n  "scripts": {{\n    {0}\n  }}\n}}\n',
  cf14: '{{\n  "name": "{0}",\n  "scripts": {{\n    "dev": "{1}",\n    "build": "{2}"\n  }}\n}}\n',
  cf15: '{{\n  "name": "{0}",\n  "main": "{1}",\n  "scripts": {{\n    "start": "{2}"\n  }}\n}}\n',

  // ========== HTTP / 请求（ht1-ht20）==========
  ht1: "fetch('{0}')\n",
  ht2: "fetch('{0}', {\n  method: 'POST',\n  headers: {1},\n  body: JSON.stringify({2})\n})\n",
  ht3: 'fetch({0})\n  .then(res => res.json())\n  .then(data => {1})\n',
  ht4: 'const res = await fetch({0})\n',
  ht5: 'const data = await res.json()\n',
  ht6: "axios.get('{0}')\n",
  ht7: "axios.post('{0}', {1})\n",
  ht8: "axios.get('{0}').then(res => {1})\n",
  ht9: 'const res = await axios.get({0})\n',
  ht10: 'const res = await axios.post({0}, {1})\n',
  ht11: '{"Content-Type": "application/json"}\n',
  ht12: '{"Authorization": "Bearer " + {0}}\n',
  ht13: 'const controller = new AbortController()\n',
  ht14: 'signal: controller.signal\n',
  ht15: 'headers: {0}\n',
  ht16: 'method: \'POST\'\n',
  ht17: 'method: \'GET\'\n',
  ht18: 'method: \'PUT\'\n',
  ht19: 'method: \'DELETE\'\n',
  ht20: 'body: JSON.stringify({0})\n',

  // ========== 测试 / 断言（ts1-ts15）==========
  ts1: "import { test, expect } from 'vitest'\n",
  ts2: "import { describe, it, expect } from 'vitest'\n",
  ts3: "import { beforeEach, afterEach } from 'vitest'\n",
  ts4: "import { test, expect } from '@playwright/test'\n",
  ts5: 'test(\'{0}\', () => {\n  {1}\n})\n',
  ts6: 'test(\'{0}\', async () => {\n  {1}\n})\n',
  ts7: 'describe(\'{0}\', () => {\n  {1}\n})\n',
  ts8: 'it(\'should {0}\', () => {\n  {1}\n})\n',
  ts9: 'expect({0}).toBe({1})\n',
  ts10: 'expect({0}).toEqual({1})\n',
  ts11: 'expect({0}).toBeTruthy()\n',
  ts12: 'expect({0}).toBeFalsy()\n',
  ts13: 'expect({0}).toBeNull()\n',
  ts14: 'expect({0}).toBeUndefined()\n',
  ts15: 'expect({0}).toContain({1})\n',

  // ========== 常用模板片段（ft1-ft20）==========
  ft1: 'const {0} = await {1}\n',
  ft2: 'const {0} = await {1}.json()\n',
  ft3: 'const { data } = await {0}\n',
  ft4: 'const {0} = {1}[\'{2}\']\n',
  ft5: 'const {0} = {1}.{2}\n',
  ft6: 'const {0} = {1}({2})\n',
  ft7: 'const {0} = new {1}({2})\n',
  ft8: 'const {0} = await import(\'{1}\')\n',
  ft9: 'const {0} = typeof {1} !== \'undefined\' ? {1} : {2}\n',
  ft10: 'const {0} = {1} ?? {2}\n',
  ft11: 'const {0} = {1} ? {2} : {3}\n',
  ft12: 'const {0} = {1} || {2}\n',
  ft13: 'const {0} = {1} && {2}\n',
  ft14: 'if (!{0}) {\n  {1}\n}\n',
  ft15: 'if (!{0}) return {1}\n',
  ft16: 'if ({0}) return {1}\n',
  ft17: 'if (!{0}) throw new Error(\'{1}\')\n',
  ft18: 'const {0} = process.env.{1} || \'{2}\'\n',
  ft19: 'const {0} = parseInt(process.env.{1} || \'{2}\', 10)\n',
  ft20: 'const {0} = Boolean(process.env.{1})\n',

  // ========== TypeScript 高级类型（ty1-ty15）==========
  ty1: 'type {0} = {1} & {2}\n',
  ty2: 'type {0} = {1} | {2}\n',
  ty3: 'type {0}<T> = T extends {1} ? {2} : {3}\n',
  ty4: 'type {0} = {1}[\'{2}\']\n',
  ty5: 'type {0} = keyof {1}\n',
  ty6: 'type {0} = Partial<{1}>\n',
  ty7: 'type {0} = Required<{1}>\n',
  ty8: 'type {0} = Readonly<{1}>\n',
  ty9: 'type {0} = Pick<{1}, {2}>\n',
  ty10: 'type {0} = Omit<{1}, {2}>\n',
  ty11: 'type {0} = Record<{1}, {2}>\n',
  ty12: 'type {0} = Awaited<{1}>\n',
  ty13: 'type {0} = ReturnType<{1}>\n',
  ty14: 'type {0} = Parameters<{1}>\n',
  ty15: 'type {0} = NonNullable<{1}>\n',

  // ========== Python 进阶 2（pa1-pa15）==========
  pa1: 'with {0} as {1}:\n    {2}\n',
  pa2: '@contextmanager\ndef {0}():\n    {1}\n',
  pa3: '@property\ndef {0}(self):\n    {1}\n',
  pa4: '@{0}.getter\ndef {1}(self):\n    {2}\n',
  pa5: '@{0}.setter\ndef {1}(self, value):\n    {2}\n',
  pa6: 'def __repr__(self):\n    return {0}\n',
  pa7: 'def __str__(self):\n    return {0}\n',
  pa8: 'def __len__(self):\n    return {0}\n',
  pa9: 'def __eq__(self, other):\n    return {0}\n',
  pa10: 'def __hash__(self):\n    return {0}\n',
  pa11: 'def __iter__(self):\n    return {0}\n',
  pa12: 'def __next__(self):\n    return {0}\n',
  pa13: 'def __enter__(self):\n    return {0}\n',
  pa14: 'def __exit__(self, *args):\n    {0}\n',
  pa15: 'def __call__(self, {0}):\n    {1}\n',

  // ========== Git 命令（g1-g20）==========
  g1: 'git init\n',
  g2: 'git clone {0}\n',
  g3: 'git status\n',
  g4: 'git add .\n',
  g5: 'git add {0}\n',
  g6: 'git commit -m "{0}"\n',
  g7: 'git push origin {0}\n',
  g8: 'git pull origin {0}\n',
  g9: 'git checkout {0}\n',
  g10: 'git checkout -b {0}\n',
  g11: 'git branch\n',
  g12: 'git branch {0}\n',
  g13: 'git merge {0}\n',
  g14: 'git rebase {0}\n',
  g15: 'git log --oneline\n',
  g16: 'git log --oneline -{0}\n',
  g17: 'git diff\n',
  g18: 'git diff {0}\n',
  g19: 'git remote add origin {0}\n',
  g20: 'git remote -v\n',

  // ========== npm / yarn / pnpm（np1-np15）==========
  np1: 'npm install\n',
  np2: 'npm install {0}\n',
  np3: 'npm install -D {0}\n',
  np4: 'npm install -g {0}\n',
  np5: 'npm uninstall {0}\n',
  np6: 'npm update\n',
  np7: 'npm run {0}\n',
  np8: 'npm run dev\n',
  np9: 'npm run build\n',
  np10: 'npm run test\n',
  np11: 'npm run lint\n',
  np12: 'npm publish\n',
  np13: 'npx {0}\n',
  np14: 'yarn add {0}\n',
  np15: 'pnpm add {0}\n',

  // ========== Docker（dk1-dk10）==========
  dk1: 'FROM node:{0}\n',
  dk2: 'FROM python:{0}\n',
  dk3: 'WORKDIR /app\n',
  dk4: 'COPY package*.json ./\n',
  dk5: 'RUN npm install\n',
  dk6: 'COPY . .\n',
  dk7: 'EXPOSE {0}\n',
  dk8: 'CMD ["node", "{0}"]\n',
  dk9: 'CMD ["python", "{0}"]\n',
  dk10: 'docker build -t {0} .\n'
}

/**
 * 模板总数（动态计算，确保准确）
 */
export const OPENX_TEMPLATE_COUNT = Object.keys(OPENX_PRESET_TEMPLATES).length

/**
 * OpenX 核心模板子集（注入 system prompt 的高频高价值模板 ID）
 *
 * 设计动机：完整 807 模板注入 system prompt 约消耗 ~9800 token，远超 OpenX
 * 压缩输出所能节省的量，形成自我抵消。改为只注入 ~150 个最高频模板（覆盖
 * 工具调用 / TS / React / Python / JSON / 操作符 / 常用短语），注入开销
 * 降至 ~1500 token（↓87%），而压缩能力基本不损——AI 对未注入的模板可用
 * OX{def:ID} 自定义。解码器仍注册全部 807 模板（向后兼容旧会话引用）。
 *
 * 选取原则：
 * 1. 工具调用模板全量注入（每次工具调用都受益，压缩 JSON arguments）
 * 2. 各语言选取最高频的声明 / 控制流 / 异步 / 集合操作
 * 3. 覆盖项目实际技术栈（Electron / React / Python MCP / JSON 结构化输出）
 */
export const OPENX_CORE_IDS: readonly string[] = [
  // ===== 工具调用（全量，压缩 JSON arguments，最高价值）=====
  'x01', 'x02', 'x03', 'x04', 'x05', 'x06', 'x07', 'x08', 'x09', 'x10',
  'x11', 'x12', 'x13', 'x14', 'x15', 'x16', 'x17', 'x18', 'x19', 'x20',
  'x21', 'x22', 'x23', 'x24', 'x25', 'x26', 'x27', 'x28', 'x29', 'x30',
  'x31', 'x32', 'x33', 'x34', 'x35', 'x36', 'x37', 'x38', 'x39', 'x40',
  // ===== TypeScript / JavaScript 基础（import / export / 声明 / 控制流 / Promise / console）=====
  't01', 't02', 't03', 't05', 't08', 't10', 't11', 't13', 't14', 't15',
  't16', 't17', 't19', 't21', 't23', 't24', 't25', 't27', 't28', 't29',
  't31', 't33', 't34', 't35', 't38', 't39', 't42', 't43', 't45', 't46',
  't53', 't55', 't64', 't68', 't70', 't73', 't78', 't79', 't80',
  // ===== React（hooks / 组件 / JSX）=====
  'r01', 'r02', 'r03', 'r04', 'r05', 'r06', 'r10', 'r12', 'r14', 'r15',
  'r16', 'r17', 'r20', 'r21', 'r22', 'r24', 'r32', 'r33', 'r35', 'r40',
  'r41', 'r42', 'r43', 'r44', 'r47', 'r48', 'r49',
  // ===== Python（def / class / 控制流 / async / 推导式 / 内建）=====
  'p01', 'p02', 'p05', 'p06', 'p07', 'p08', 'p09', 'p10', 'p11', 'p12',
  'p19', 'p20', 'p22', 'p23', 'p27', 'p28', 'p32', 'p33', 'p34', 'p38',
  'p39', 'p41', 'p47', 'p48', 'p51', 'p53', 'p60', 'p66', 'p71', 'p79',
  'p97', 'p99',
  // ===== JSON 结构化输出 =====
  'j01', 'j02', 'j03', 'j05', 'j07', 'j08', 'j09', 'j11', 'j12', 'j13',
  'j14', 'j15'
  // 注：操作符(o)/短语(z/e)系列模板过短（len < OX{ID} 标记长度），
  // 用 OX{} 反而增加 token（净负压缩），故不注入核心集；
  // 解码器仍保留它们，AI 可按需用 OX{def:} 自定义等价模式
]

/**
 * 核心模板字典（OPENX_CORE_IDS 对应的模板子集，用于注入 system prompt）
 */
export const OPENX_CORE_TEMPLATES: Record<string, string> = OPENX_CORE_IDS.reduce(
  (acc, id) => {
    if (OPENX_PRESET_TEMPLATES[id] !== undefined) {
      acc[id] = OPENX_PRESET_TEMPLATES[id]
    }
    return acc
  },
  {} as Record<string, string>
)

/** 核心模板数量（注入提示词的模板数） */
export const OPENX_CORE_COUNT = OPENX_CORE_IDS.filter(
  (id) => OPENX_PRESET_TEMPLATES[id] !== undefined
).length
